// <auto-generated />
using System;
using EStoreAdminRepository.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreAdminRepository.Migrations
{
    [DbContext(typeof(BrandRepository))]
    partial class BrandRepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EStoreAdminModel.Models.BrandModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7caf4556-58b0-4f99-8590-5fe3342e377b"),
                            Name = "Reliance"
                        },
                        new
                        {
                            Id = new Guid("3e28d499-205b-4060-af45-5149ea49a632"),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("fff83be7-2dbf-4934-87da-bc18264f0bc8"),
                            Name = "Airtel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
