// <auto-generated />
using System;
using EStoreAdminRepository.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EStoreAdminRepository.Migrations.TypeRepositoryMigrations
{
    [DbContext(typeof(TypeRepository))]
    [Migration("20260713041115_TypesMigration")]
    partial class TypesMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EStoreAdminModel.Models.Types.TypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("165dc7d9-023f-486d-bf49-efbb5b497edc"),
                            Name = "Gadgets"
                        },
                        new
                        {
                            Id = new Guid("2df9493d-b9cb-44fc-80b6-496ea679dc0d"),
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("7be12499-133e-4290-a652-666a5a7fe387"),
                            Name = "Television"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
